spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/vur?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
server:
  port: 8088
  compression:
    enabled: true